- .github/workflows/setup-and-validate.yml
- .gitignore
- README.md
- build.gradle.kts
- docker-compose.yml
- helm_deploy/hmpps-visit-allocation-api/values.yaml
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- helm_deploy/values-staging.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/config/AuthAwareTokenConverter.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/config/ResourceServerConfiguration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/DomainEventListenerService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/listener/DomainEventListener.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/listener/events/DomainEvent.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/listener/events/SQSMessage.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/listener/events/additionalinfo/PrisonerConvictionStatusChangedInfo.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/listener/events/deserializers/RawJsonDeserializer.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/listener/processors/PrisonerConvictionStatusChangeProcessor.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/listener/processors/PrisonerConvictionStatusUpdatedProcessor.kt
- src/main/resources/application-dev.yml
- src/main/resources/application.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/integration/OpenApiDocsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/integration/ResourceSecurityTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/integration/domainevents/EventsIntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/integration/domainevents/EventsSqsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/integration/domainevents/LocalStackContainer.kt
- src/test/resources/application-test.yml
Add the ability for the visit-allocation-api to listen to the prison visits events SNS topic on a new SQS queue. Add processor to consume the message from the queue and transform it into a class.
Add TODO comment to remember to hook up the call to new allocation service (next change in this feature).
## JIRA Link
https://dsdmoj.atlassian.net/browse/VB-5084
> VB-5084 - Allow SQS message handling for domain events

- helm_deploy/hmpps-visit-allocation-api/values.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/sqs/VisitAllocationEventJobSqsService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/sqs/VisitAllocationPrisonerRetrySqsService.kt
Our visit-allocation-api wasn't deploying to dev. It was failing due to multiple reasons.
1. The SQS queue name wasn't loading in correctly.
2. The IRSA policies were missing from cloud-platform-environments, which meant we were getting AWS auth errors.
1. To fix this, we used findQueueById instead of by name.
2. We had to add the policies and add a custom service-account to the values.yaml file in helm_deploy.
> Fix SQS deployment issues

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/AllocationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/VisitAllocationByPrisonJobListenerService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/integration/events/DomainEventsSqsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/integration/events/PrisonerRetryQueueHandlerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/integration/events/VisitAllocationByPrisonJobSqsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/integration/wiremock/IncentivesMockServer.kt
replace first with firstOrNull as a fix for "Collection contains no element matching the predicate." error
> AllocationService bug fix - replace first with firstOrNull

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/controller/NomisSyncController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/dto/nomis/VisitAllocationPrisonerSyncDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/enums/ChangeLogType.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/enums/NegativeVisitOrderStatus.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/enums/NegativeVisitOrderType.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/enums/VisitOrderStatus.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/enums/nomis/ChangeLogSource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/model/entity/ChangeLog.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/model/entity/NegativeVisitOrder.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/model/entity/PrisonerDetails.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/model/entity/VisitOrder.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/repository/ChangeLogRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/repository/NegativeVisitOrderRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/repository/PrisonerDetailsRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/repository/VisitOrderRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/AllocationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/ChangeLogService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/NomisSyncService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/PrisonerDetailsService.kt
- src/main/resources/db/migration/V1_5__create_negative_visit_order_table.sql
- src/main/resources/db/migration/V1_6__create_visit_order_change_log_table.sql
- src/main/resources/db/migration/V1_7__add_index_to_visit_order_change_log_table.sql
- src/main/resources/db/migration/V1_8__create_prisoner_details_table.sql
- src/main/resources/db/migration/V1_9__alter_date_to_timestamp_visit_order_table.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/integration/NomisSyncControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/integration/allocations/AllocationServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/integration/events/EventsIntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/integration/events/PrisonerRetryQueueHandlerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/integration/events/VisitAllocationByPrisonJobSqsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/integration/helper/EntityHelper.kt
Initial migration to onboard a prisoner from NOMIS to dps.
This PR includes a new service, handling migrating a balance of both positive and negative values.
In the current system design, negative VOs are represented as their own model with unique status and types.
We also capture the prisoner's details (currently, lastAllocatedDate) to help us with allocations on our service.
Add integration tests to cover new migration logic.
https://dsdmoj.atlassian.net/browse/VB-5220
> VB-5220 - Migrate a prisoner balance

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/dto/nomis/VisitAllocationPrisonerMigrationDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/NomisMigrationService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/integration/NomisControllerMigrateTest.kt
Some prisoners on NOMIS have a balance but don't have an IEP allocation date. This change allows those prisoners to be migrated.
If a null date is found, we set it to TODAY - 28 DAYS, to get as close to next IEP allocation date as possible for prisoner.
https://dsdmoj.atlassian.net/browse/VB-5298
> VB-5298 - Make lastVoAllocationDate optional

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/config/VisitAllocationApiExceptionHandler.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/dto/nomis/VisitAllocationPrisonerSyncDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/exception/InvalidSyncRequestException.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/NomisSyncService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/NomisSyncServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/integration/NomisControllerSyncTest.kt
When a sync request comes in, sometimes it's only for a VO or only for a PVO. We are updating our code to account for this. Now we will only process VOs if oldVoBalance is present and PVOs if oldPvoBalance is present.
> Update sync endpoint to allow vo and pvo balances to be nullable

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/repository/NegativeVisitOrderRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/AllocationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/NomisSyncService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/AllocationServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/NomisSyncServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/integration/NomisControllerSyncTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/integration/events/EventsIntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/integration/events/PrisonerRetryQueueHandlerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/integration/events/VisitAllocationByPrisonJobSqsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/integration/helper/EntityHelper.kt
When a balance of a prisoner is negative, first repay the prisoners balance before generating new allocation.
https://dsdmoj.atlassian.net/browse/VB-5297
> VB-5297 - Allocation handles prisoners with negative balances

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/NomisSyncService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/integration/NomisControllerSyncTest.kt
Originally it was only saving their details if it was an IEP adjustment. However, we need to do an initial save for the prisoner if they didn't come through the migration, for any adjustment reason.
> Fix - Save prisoner details onto api if they are new

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/repository/NegativeVisitOrderRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/repository/PrisonerDetailsRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/repository/VisitOrderRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/NomisMigrationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/PrisonerDetailsService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/integration/NomisControllerMigrateTest.kt
Without doing this, we could end up creating the wrong amount of positive / negative VOs (scenario when sync event comes in first).
> Fix - Migration needs to reset a prisoner if they exist

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/controller/NomisController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/dto/nomis/VisitAllocationPrisonerSyncBookingDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/enums/ChangeLogType.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/repository/ChangeLogRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/BalanceService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/ChangeLogService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/NomisSyncService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/NomisSyncServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/integration/NomisControllerSyncBookingTest.kt
In NOMIS, a booking can be moved between 2 prisoners. As the VO/PVO balance is stored against bookings on NOMIS, moving it can change the balance.
This endpoint allows NOMIS to tell visit-allocation-api of the change so it can sync.
https://dsdmoj.atlassian.net/browse/VB-5392
> VB-5392 - New endpoint to sync booking changes

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/controller/NomisController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/dto/nomis/VisitAllocationPrisonerAdjustmentRequestDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/dto/nomis/VisitAllocationPrisonerAdjustmentResponseDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/model/entity/ChangeLog.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/model/entity/PrisonerDetails.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/repository/ChangeLogRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/repository/PrisonerDetailsRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/BalanceService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/ChangeLogService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/NomisMigrationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/NomisSyncService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/PrisonerDetailsService.kt
- src/main/resources/db/migration/V1_11__alter_change_log_table_add_balance_columns.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/NomisSyncServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/integration/NomisControllerGetAdjustmentTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/integration/NomisControllerSyncTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/integration/events/DomainEventsBookingMovedTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/integration/events/DomainEventsPrisonerConvictionStatusChangedTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/integration/events/DomainEventsPrisonerMergedTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/integration/events/DomainEventsPrisonerReceivedTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/integration/events/DomainEventsPrisonerReleasedTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/integration/events/EventsIntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/integration/helper/EntityHelper.kt
This PR aims to capture the prisoners balance at every point it changes via logging in the change_log table.
It also adds a new endpoint to the NOMIS Controller, which allows NOMIS to get a prisoners adjustment by providing the prisoner ID and adjustment ID (/visits/allocation/prisoner/{prisonerId}/adjustments/{adjustmentId}
This new endpoint will be used in near future when we begin publishing events for each prisoner that has a balance change, allowing NOMIS to stay in sync (2-way sync, DPS -> NOMIS).
> VB-5514 - Capture prisoner balance in change log table

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/enums/ChangeLogType.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/model/entity/PrisonerDetails.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/model/entity/VisitOrderAllocationPrisonJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/repository/VisitOrderAllocationPrisonJobRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/AllocationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/ChangeLogService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/PrisonService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/PrisonerRetryService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/ProcessPrisonerService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/listener/VisitAllocationPrisonerRetryQueueListener.kt
- src/main/resources/db/migration/V1_12__alter_allocation_prison_job_failed_column_name.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/ProcessPrisonerServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/integration/events/EventsIntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/integration/events/PrisonerRetryQueueHandlerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/integration/events/VisitAllocationByPrisonJobSqsTest.kt
Ready for when we need to publish event per prisoner after processing, we need to ensure the prisoners transaction has fully committed before raising the event.
> Move prisoner processing into separate class with managed transaction

- README.md
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- helm_deploy/values-staging.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/config/VisitAllocationApiExceptionHandler.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/exception/PublishEventException.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/AllocationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/DomainEventListenerService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/PrisonerRetryService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/SnsService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/sqs/VisitAllocationEventJobSqsService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/sqs/VisitAllocationPrisonerRetrySqsService.kt
- src/main/resources/application.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/integration/events/EventsIntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/integration/events/PrisonerRetryQueueHandlerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/integration/events/SnsDisabledTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/integration/events/SnsEnabledEventsSentTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/integration/events/VisitAllocationByPrisonJobSqsTest.kt
- src/test/resources/application-test.yml
when a prisoners balance changes due to our nightly allocation (or via retry queue processing). We now raise an event which allows NOMIS to consume, call our service and get the new balance information for that prisoner.
https://dsdmoj.atlassian.net/browse/VB-5235
> Domain event raising on allocation API

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/PrisonerDetailsService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/ProcessPrisonerService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/integration/NomisControllerMigrateTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/integration/events/DomainEventsBookingMovedTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/integration/events/PrisonerRetryQueueHandlerTest.kt
The change_log was not persisting, changed how we get it via capturing the saved prisoner returned and getting the entry from the changeLog list.
> Change how we return the changeLog entry on prisoner process service

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/ProcessPrisonerService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/listener/events/additionalinfo/PrisonerConvictionStatusChangedInfo.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/integration/events/DomainEventsVisitCancelledTest.kt
Fix code after discussions. If during cancel event no VO is found associated with the visit, then simply create a new VO for them.
https://dsdmoj.atlassian.net/browse/VB-5475
> VB-5475 - Visit cancelled event

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/repository/PrisonerDetailsRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/BalanceService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/PrisonerDetailsService.kt
Sometimes requests come in within a few milliseconds of each other. This PR aims to add a simple lock on the row, forcing other requests to wait for the first transaction to close before allowing them to grab the latest prisoner_details.
> Add row locking for prisoner_details

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/NomisMigrationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/NomisSyncService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/NomisSyncServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/integration/NomisControllerMigrateTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/integration/NomisControllerSyncTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/integration/events/DomainEventsBookingMovedTest.kt
Remove the manual call to save the updated prisoner details, as this was overwriting hibernates management of the entity and causing data to be wiped if two requests came in at the same time.
This is part 1 of the fix, to sort out the nomis sync endpoints first. I'll next sort the dps allocation side (which isn't in use yet).
> Bug fix - Remove manual management of prisoner details entity

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/model/entity/ChangeLog.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/repository/ChangeLogRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/AllocationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/ChangeLogService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/PrisonerDetailsService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/PrisonerRetryService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/ProcessPrisonerService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/listener/events/handlers/PrisonerMergedEventHandler.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/listener/events/handlers/PrisonerReceivedEventHandler.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/listener/events/handlers/VisitBookedEventHandler.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/listener/events/handlers/VisitCancelledEventHandler.kt
- src/main/resources/db/migration/V1_17__alter_change_log_table_add_reference_column.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/ProcessPrisonerServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/integration/NomisControllerGetAdjustmentTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/integration/events/DomainEventsVisitBookedTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/integration/events/DomainEventsVisitCancelledTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/integration/events/PrisonerRetryQueueHandlerTest.kt
Remove the manual call to save the updated prisoner details, as this was overwriting hibernates management of the entity and causing data to be wiped if two requests came in at the same time.
https://github.com/ministryofjustice/hmpps-visit-allocation-api/pull/118
> Fix Bug - Overwriting data part 2

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/controller/NomisController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/NomisMigrationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/NomisService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/NomisSyncService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/PrisonerDetailsService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/ProcessPrisonerService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/listener/events/handlers/PrisonerBookingMovedEventHandler.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/listener/events/handlers/PrisonerMergedEventHandler.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/listener/events/handlers/PrisonerReceivedEventHandler.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/listener/events/handlers/VisitBookedEventHandler.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/listener/events/handlers/VisitCancelledEventHandler.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/integration/NomisControllerMigrateTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/integration/events/DomainEventsBookingMovedTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/integration/events/DomainEventsPrisonerMergedTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/integration/events/DomainEventsPrisonerReceivedTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/integration/events/PrisonerRetryQueueHandlerTest.kt
To avoid race conditions on inserting new prisoners, put the creation logic into it's own transaction.
> Move prisoner creation into isolated transaction

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/controller/NomisController.kt
This PR updates the description of the migrate endpoint to inform users that the endpoint is used for 2 purposes.
1. Initial migration for a new prisoner.
2. To re-setup a prisoners balance when an IEP Entitlement sync happens on NOMIS side. They needed to reset the balance and not use the sync endpoint, so this seemed like the best endpoint for that purpose.
> Add comment to better describe endpoint

- .github/workflows/pipeline.yml
Sets the slack_notification flag to true for prod releases. It uses the ENV var set in GitHub -> Settings -> Variables, PROD_SLACK_RELEASE which we've set to visits-releases.
> Add slack channel release notification

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/dto/snapshots/VOSnap.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/model/entity/ChangeLog.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/model/entity/NegativeVisitOrder.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/model/entity/PrisonerDetails.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/model/entity/VisitOrder.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/ProcessPrisonerService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/utils/PrisonerChangeTrackingUtil.kt
We believe a data issue is happening where requests are removing previous requests saved child objects due to issues with using data classes and their default equals / hashcode methods in kotlin. Hibernate seems to be marking the old objects are orphans and cleaning them up incorrectly.
Fix: Add overrides for each of the equals / hashcode methods. Also remove the use of deepCopy as this could cause issues in the future if a dev accidentally called to save this copied object.
> Bug - Issue with Hibernate, JPA, data classes and orphanRemoval = true

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/clients/PrisonerSearchClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/AllocationService.kt
- src/main/resources/application.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/integration/events/VisitAllocationByPrisonJobSqsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/integration/wiremock/PrisonerSearchMockServer.kt
- src/test/resources/application-test.yml
Reduce page size on prisoner search /attribute-search to 100 from 10000 as it seems to fail when a big number of results are returned for prisons with a big capacity.
> VB-5977 - Handle failure for prisons with large convicted prison capacity

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/clients/PrisonerSearchClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/dto/prisoner/search/AttributeSearchPrisonerDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/AllocationService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/integration/wiremock/PrisonerSearchMockServer.kt
Paging provides unstable results, to get around this we use the query parameter requestFields and pass in the single field we want back (their prisoner number). This avoids web client memory buffer exceptions and avoids the unstable results from paging
> Use custom requestFields parameter to avoid overfetching

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/listener/DomainEventListener.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/listener/VisitAllocationByPrisonJobListener.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/service/listener/VisitAllocationPrisonerRetryQueueListener.kt
Currently all jobs from this queue process as 1 span, and are given the same operation_id, making it impossible to search the logs.
This PR aims to split each job to have it's own span, making logging much cleaner on Azure.
> Attempt to split each jobs telemetry into their own spans

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/model/entity/PrisonerDetails.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/integration/PrisonerDetailsRetrievalTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitallocationapi/integration/events/DomainEventsBookingMovedTest.kt
Exclude expired VOs from being EAGER loaded when prisoner is loaded in, to avoid bloating the collections with VOs which won't be actioned in any way.
> Exclude pulling back expired VOs in eager loading to improve performance
